# Generated by Django 3.1.2 on 2020-10-09 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=150, verbose_name='post id in source')),
                ('author_id', models.CharField(max_length=150, verbose_name='author id in source')),
                ('url', models.URLField(verbose_name='post url in source')),
                ('text', models.TextField(db_index=True, verbose_name='post text')),
                ('likes', models.PositiveIntegerField(verbose_name='post likes count')),
                ('comments', models.PositiveIntegerField(verbose_name='post comments count')),
                ('reposts', models.PositiveIntegerField(verbose_name='post reposts count')),
                ('views', models.PositiveIntegerField(verbose_name='post views count')),
                ('pub_date', models.DateTimeField(verbose_name='post publication date')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='source name')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
            options={
                'verbose_name_plural': 'spam',
                'db_table': 'spam',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='report title')),
                ('rule', models.CharField(max_length=100, verbose_name='the rule by which records are selected')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='period start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='period end date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completeness of creating report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url of attached image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.post')),
            ],
            options={
                'db_table': 'post_images',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.report'),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.source'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
            options={
                'verbose_name_plural': 'archive',
                'db_table': 'archive',
            },
        ),
    ]
